language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - python setup.py install
  - pip install coveralls --use-mirrors

script:
  - sudo apt-get install -qq gdb
  - nosetests -q --with-coverage --cover-erase --cover-package=pyrasite

after_success:
  - coveralls
